/* This file is part of file-browser.
 *
 * Copyright (C)
 *  2018 Alexander Haase <ahaase@alexhaase.de>
 *
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * Webpack encore configuration file.
 *
 * This file contains the general configuration for webpack encore to build all
 * assets required by this applications and its themes.
 */

var Encore = require('@symfony/webpack-encore');
Encore
    /* Assets will be copied into 'public/assets'. However, the public path will
     * be just '/assets'. */
    .setOutputPath('public/assets/')
    .setPublicPath('/assets')

    /* Before each build, the output path will be cleared. To flush all caches,
     * the assets will be versioned, forcing a reload whenever the asset's
     * contents change. */
    .cleanupOutputBeforeBuild()
    .enableVersioning(Encore.isProduction())

    /* Enable required dependencies for generating the assets. */
    .enableLessLoader()

    /* Define all assets that should be generated by webpack.
     *
     * NOTE: Webpack is meant for JavaScript and can't handle CSS only targets.
     *       If just a CSS file should be generated, an extra JavaScript file
     *       will be generated. However, this file can be just omitted. */
    .addEntry('theme', './assets/css/theme.less')

    /* In the development environment, a source map should be generated. The
     * source map will be appended to the file's contents. */
    .enableSourceMaps(!Encore.isProduction());

/* Export the final configuration. */
module.exports = Encore.getWebpackConfig();
